# Generated by Django 5.2.4 on 2025-07-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_pokemonentity_defence_pokemonentity_health_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='title',
            new_name='title_ru',
        ),
    ]
