# Generated by Django 5.2.4 on 2025-08-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_rename_title_pokemon_title_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default='er'),
            preserve_default=False,
        ),
    ]
